### ISSUE TITLE
Refactor osu!direct

### ISSUE THREAD

**Issue by RealistikDash** [RealistikOsu/USSR#5]
With direct being one of the first systems being implemented, it has fallen behind the standard for the score server. A new refactor would ideally consider:
- Being split into more reusable functions and/or classes.
- Have bancho mirroring be optional (within the config)
- [Optional] Support account pools with a sort of load balancer between each.
- Raw mirror support (302)

**Comment by RealistikDash** [comment]
Wake up @lenforiee

**Comment by xSkyyy** [comment]
Wake up @lenforiee

**Comment by RealistikDash** [comment]
Done by lenforiee
